//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class cambios : global::System.Configuration.ApplicationSettingsBase {
        
        private static cambios defaultInstance = ((cambios)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new cambios())));
        
        public static cambios Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("primero")]
        public string dato1 {
            get {
                return ((string)(this["dato1"]));
            }
            set {
                this["dato1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClaveProducto {
            get {
                return ((string)(this["ClaveProducto"]));
            }
            set {
                this["ClaveProducto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FechaVencimiento {
            get {
                return ((string)(this["FechaVencimiento"]));
            }
            set {
                this["FechaVencimiento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ESTO VA A SER UN TITULO LARGO PARA VER QUE PASA")]
        public string TituloTicket {
            get {
                return ((string)(this["TituloTicket"]));
            }
            set {
                this["TituloTicket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NO NEGOCIABLE")]
        public string Linea1 {
            get {
                return ((string)(this["Linea1"]));
            }
            set {
                this["Linea1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NO REEMBOLSABLE")]
        public string Linea2 {
            get {
                return ((string)(this["Linea2"]));
            }
            set {
                this["Linea2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NO RECLAMABLE")]
        public string Linea3 {
            get {
                return ((string)(this["Linea3"]));
            }
            set {
                this["Linea3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pablodelhip@gmail.com")]
        public string Correo {
            get {
                return ((string)(this["Correo"]));
            }
            set {
                this["Correo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NumeroMensajesSMS {
            get {
                return ((int)(this["NumeroMensajesSMS"]));
            }
            set {
                this["NumeroMensajesSMS"] = value;
            }
        }
    }
}
